---
abstract: 'plugin for generating passwords on IRC'
author:
  - "Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-Data-SimplePassword
provides:
  POE::Component::IRC::Plugin::Data::SimplePassword:
    file: lib/POE/Component/IRC/Plugin/Data/SimplePassword.pm
    version: 0.0102
requires:
  POE::Component::Data::SimplePassword: 0.0101
  POE::Component::IRC::Plugin::BasePoCoWrap: 0.005
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.0102
